// The 49 records of the 1983 original with their original numbers (docs/diktator/research/original-rules.md),
// re-themed for Zog's Albania. Russians → Itálie, Americans → Británie, Leftoto → Jugoslávie.

import type { Decision, NewsItem, Petition } from '../../logic/records';

export const PETITIONS: readonly Petition[] = [
  // Armáda (1–8)
  { id: 'p01', from: 'armada', origin: 'original', title: 'Zavést povinnou vojenskou službu',
    effects: { monthly: 5, pop: { armada: 4, rolnici: -3, statkari: -1 }, str: { armada: 3, rolnici: -2, statkari: -1 } } },
  { id: 'p02', from: 'armada', origin: 'original', title: 'Zabrat statkářům půdu pro cvičiště',
    effects: { pop: { armada: 3, statkari: -3 }, str: { armada: 1, statkari: -1 } } },
  { id: 'p03', from: 'armada', origin: 'original', title: 'Zaútočit na všechny tábory povstalců v horách',
    effects: { cost: -100, pop: { armada: 3, rolnici: -1, statkari: 1, jugoslavie: -1, italie: -1 }, str: { armada: 1, statkari: 1, povstalci: -4 } } },
  { id: 'p04', from: 'armada', origin: 'original', title: 'Zaútočit na tábory povstalců za jugoslávskou hranicí',
    effects: { cost: -80, pop: { armada: 3, rolnici: -1, jugoslavie: -4, italie: -1 }, str: { armada: 1, statkari: 1, povstalci: -2 } } },
  { id: 'p05', from: 'armada', origin: 'original', title: 'Odvolat velitele tajné policie',
    effects: { pop: { armada: 4, rolnici: 2, statkari: 1, policie: -4 }, str: { armada: 1, statkari: 1, policie: -3 } } },
  { id: 'p06', from: 'armada', origin: 'original', title: 'Vyhostit italské vojenské poradce',
    effects: { pop: { armada: 3, jugoslavie: -1, italie: -4, britanie: 2 } } },
  { id: 'p07', from: 'armada', origin: 'original', title: 'Zvýšit vojákům žold',
    effects: { monthly: 9, pop: { armada: 4, statkari: -1 }, str: { armada: 2, rolnici: -1, statkari: -1, povstalci: -1 } } },
  { id: 'p08', from: 'armada', origin: 'original', title: 'Nakoupit více pušek a střeliva',
    effects: { cost: -120, pop: { armada: 4, rolnici: -1, statkari: -1, jugoslavie: -1, policie: -1 }, str: { armada: 3, rolnici: -1, statkari: -1, povstalci: -2, jugoslavie: -1 } } },
  // Rolníci (9–16)
  { id: 'p09', from: 'rolnici', origin: 'original', title: 'Zastavit násilné odvody mladých mužů do armády',
    effects: { pop: { armada: -1, rolnici: 2, statkari: 1 }, str: { armada: -1, povstalci: -1 } } },
  { id: 'p10', from: 'rolnici', origin: 'original', title: 'Zvýšit nejnižší mzdu',
    effects: { pop: { rolnici: 4, statkari: -4, jugoslavie: 1 }, str: { rolnici: 2, statkari: -1 } } },
  { id: 'p11', from: 'rolnici', origin: 'original', title: 'Omezit pravomoci tajné policie',
    effects: { monthly: -3, pop: { armada: 1, rolnici: 4, statkari: 2, policie: -4 }, str: { armada: 1, rolnici: 1, statkari: 1, povstalci: 1, policie: -3 } } },
  { id: 'p12', from: 'rolnici', origin: 'original', title: 'Nepouštět k nám dělníky z Jugoslávie',
    effects: { pop: { rolnici: 3, statkari: -2, jugoslavie: -2 }, str: { rolnici: 2, statkari: -2 } } },
  { id: 'p13', from: 'rolnici', origin: 'original', title: 'Zavést bezplatné školy pro všechny děti',
    effects: { cost: -100, monthly: 8, pop: { armada: -1, rolnici: 4, statkari: -2, jugoslavie: 2, policie: -1, italie: 1 }, str: { rolnici: 1, statkari: -1, povstalci: -1 } } },
  { id: 'p14', from: 'rolnici', origin: 'original', title: 'Povolit rolnické spolky a odbory',
    effects: { pop: { rolnici: 4, statkari: -3, jugoslavie: 1, policie: -1, italie: 1 }, str: { rolnici: 3, statkari: -3, policie: -1 } } },
  { id: 'p15', from: 'rolnici', origin: 'original', title: 'Propustit jejich uvězněného vůdce',
    effects: { pop: { armada: -1, rolnici: 4, statkari: -2, jugoslavie: 1, policie: -1 }, str: { rolnici: 2, statkari: -1, povstalci: -1 } } },
  { id: 'p16', from: 'rolnici', origin: 'original', title: 'Založit státní loterii',
    effects: { monthly: -6, pop: { rolnici: 3, statkari: -1 }, str: { povstalci: -1 } } },
  // Statkáři (17–24)
  { id: 'p17', from: 'statkari', origin: 'original', title: 'Zakázat armádě cvičit na jejich pozemcích',
    effects: { pop: { armada: -2, statkari: 3 }, str: { armada: -1 } } },
  { id: 'p18', from: 'statkari', origin: 'original', title: 'Snížit nejnižší mzdu',
    effects: { pop: { rolnici: -4, statkari: 4, jugoslavie: -1, italie: -1 }, str: { rolnici: -2, statkari: 2, povstalci: 1 } } },
  { id: 'p19', from: 'statkari', origin: 'original', title: 'Znárodnit britské podniky',
    effects: { cost: 100, monthly: 5, pop: { statkari: 3, jugoslavie: 1, italie: 2, britanie: -4 }, str: { statkari: 1 } } },
  { id: 'p20', from: 'statkari', origin: 'original', title: 'Uvalit clo na všechno zboží z Jugoslávie',
    effects: { monthly: -5, pop: { statkari: 3, jugoslavie: -3, italie: -1 }, str: { rolnici: 1, statkari: 2, jugoslavie: -1 } } },
  { id: 'p21', from: 'statkari', origin: 'original', title: 'Snížit výdaje na tajnou policii',
    effects: { monthly: -4, pop: { armada: 1, rolnici: 1, statkari: 3, policie: -4 }, str: { armada: 1, statkari: 1, povstalci: 1, policie: -2 } } },
  { id: 'p22', from: 'statkari', origin: 'original', title: 'Snížit vysoké pozemkové daně',
    effects: { monthly: 5, pop: { statkari: 4 }, str: { statkari: 2 } } },
  { id: 'p23', from: 'statkari', origin: 'original', title: 'Poslat vojáky pracovat na pole',
    effects: { pop: { armada: -2, rolnici: -1, statkari: 3 }, str: { armada: -1, rolnici: -1, statkari: 1, povstalci: 1 } } },
  { id: 'p24', from: 'statkari', origin: 'original', title: 'Postavit velké zavlažovací kanály',
    effects: { cost: -120, monthly: 10, pop: { armada: 1, rolnici: 1, statkari: 3, jugoslavie: -3, italie: 2, britanie: 1 }, str: { statkari: 3, jugoslavie: -2 } } },
];

export const DECISIONS: readonly Decision[] = [
  // 1 Please a group
  { id: 'd25', section: 1, origin: 'original', title: 'Jmenovat velitele armády svým zástupcem',
    effects: { pop: { armada: 4, rolnici: -1, statkari: -1, policie: -1 }, str: { armada: 1, povstalci: -1, policie: -1 } } },
  { id: 'd26', section: 1, origin: 'original', title: 'Zřídit bezplatné ošetřovny pro dělníky',
    effects: { cost: -10, monthly: 4, pop: { armada: -1, rolnici: 4, statkari: 1, jugoslavie: 2, italie: 1 }, str: { povstalci: -1 } } },
  { id: 'd27', section: 1, origin: 'original', title: 'Dát statkářům moc v krajích',
    effects: { pop: { armada: -1, rolnici: -2, statkari: 4, policie: -1, italie: -1 }, str: { armada: -1, rolnici: -1, statkari: 2, policie: -1 } } },
  { id: 'd28', section: 1, origin: 'original', title: 'Prodat britské zbraně Jugoslávii',
    effects: { cost: 50, pop: { armada: -2, jugoslavie: 4, italie: -2, britanie: 1 }, str: { armada: -1, povstalci: -1, jugoslavie: 3 } } },
  { id: 'd29', section: 1, origin: 'original', title: 'Prodat Britům právo těžit naftu',
    effects: { cost: 120, pop: { statkari: -1, jugoslavie: -1, italie: -2, britanie: 3 } } },
  { id: 'd30', section: 1, origin: 'original', title: 'Pronajmout Italům ostrov Sazan pro námořnictvo',
    effects: { monthly: -10, pop: { armada: -2, italie: 3, britanie: -3 }, str: { jugoslavie: 1 } } },
  // 2 Please all groups
  { id: 'd31', section: 2, origin: 'original', title: 'Snížit daně všem',
    effects: { monthly: 8, pop: { armada: 1, rolnici: 3, statkari: 3 }, str: { armada: -1, povstalci: -1 } } },
  { id: 'd32', section: 2, origin: 'original', title: 'Uspořádat velkou oslavnou kampaň',
    effects: { cost: -80, pop: { armada: 3, rolnici: 3, statkari: 3 }, str: { povstalci: -1 } } },
  { id: 'd33', section: 2, origin: 'original', title: 'Úplně zrušit pravomoci tajné policie',
    effects: { monthly: -8, pop: { armada: 3, rolnici: 3, statkari: 3, policie: -9 }, str: { armada: 2, rolnici: 1, statkari: 1, povstalci: 1, policie: -9 } } },
  // 3 Improve your chances
  { id: 'd34', section: 3, origin: 'original', title: 'Výrazně posílit tajnou policii',
    effects: { monthly: 6, pop: { armada: -3, rolnici: -3, statkari: -3, policie: 8 }, str: { armada: -1, rolnici: -1, statkari: -1, povstalci: -1, policie: 8 } } },
  { id: 'd35', section: 3, origin: 'original', title: 'Posílit osobní stráž', special: { kind: 'bodyguard' }, reusable: true,
    effects: { cost: -40, pop: { armada: -2, rolnici: -1, statkari: -1, policie: -1 }, str: { armada: -2, policie: -1 } } },
  { id: 'd36', section: 3, origin: 'original', title: 'Koupit letadlo pro útěk', special: { kind: 'plane' },
    effects: { cost: -120, pop: { armada: -4, rolnici: -4, statkari: -3, policie: -2 } } },
  { id: 'd37', section: 3, origin: 'original', title: 'Poslat peníze na švýcarský účet', special: { kind: 'swiss' }, reusable: true,
    effects: {} },
  // 4 Raise some cash
  { id: 'd38', section: 4, origin: 'original', title: 'Požádat Itálii o půjčku', special: { kind: 'aid', lender: 'italie' },
    effects: {} },
  { id: 'd39', section: 4, origin: 'original', title: 'Požádat Británii o pomoc', special: { kind: 'aid', lender: 'britanie' },
    effects: {} },
  { id: 'd40', section: 4, origin: 'original', title: 'Znárodnit jugoslávské podniky',
    effects: { cost: 130, pop: { armada: 1, rolnici: 1, statkari: 3, jugoslavie: -6, italie: -2 } } },
  // 5 Strengthen a group
  { id: 'd41', section: 5, origin: 'original', title: 'Koupit armádě těžká děla',
    effects: { cost: -50, pop: { armada: 3, jugoslavie: -3, italie: -1 }, str: { armada: 5, povstalci: -2, jugoslavie: -2, policie: -1 } } },
  { id: 'd42', section: 5, origin: 'original', title: 'Dovolit rolníkům volně se stěhovat',
    effects: { pop: { rolnici: 3, statkari: -1, policie: -1 }, str: { rolnici: 5, statkari: -1, povstalci: 3, policie: -1 } } },
  { id: 'd43', section: 5, origin: 'original', title: 'Dovolit statkářům soukromé ozbrojené družiny',
    effects: { pop: { armada: -1, rolnici: -1, statkari: 3, policie: -1 }, str: { armada: -1, rolnici: -1, statkari: 5, povstalci: -1, policie: -1 } } },
];

export const NEWS: readonly NewsItem[] = [
  { id: 'n44', origin: 'original', title: 'Král ztratil tajné spisy četnictva',
    effects: { pop: { policie: -4 }, str: { povstalci: 4, policie: -4 } } },
  { id: 'n45', origin: 'original', title: 'Exulanti v Bari vyzbrojili a vycvičili povstalce',
    effects: { str: { armada: -1, povstalci: 9 } } },
  { id: 'n46', origin: 'original', title: 'Neštěstí: vybuchla kasárna',
    effects: { str: { armada: -4, povstalci: 2, policie: 1 } } },
  { id: 'n47', origin: 'original', title: 'Ceny tabáku klesly o 98 %',
    effects: { str: { statkari: -3, jugoslavie: -2 } } },
  { id: 'n48', origin: 'original', title: 'Velké zemětřesení v Jugoslávii',
    effects: { str: { statkari: 2, jugoslavie: -4 } } },
  { id: 'n49', origin: 'original', title: 'Vesnice zasáhla epidemie',
    effects: { str: { rolnici: -4, statkari: -1, povstalci: -2 } } },
];
