// The 49 records of the 1983 original with their original numbers (docs/diktator/research/original-rules.md),
// re-themed for Zog's Albania. Russians → Itálie, Americans → Británie, Leftoto → Jugoslávie.

import type { Decision, NewsItem, Petition } from '../../logic/records';

export const PETITIONS: readonly Petition[] = [
  // Armáda (1–8)
  { id: 'p01', from: 'armada', origin: 'original', title: 'Zavést povinnou vojenskou službu',
    effects: { monthly: 5, pop: { armada: 4, rolnici: -3, statkari: -1 }, str: { armada: 3, rolnici: -2, statkari: -1 } } },
  { id: 'p02', from: 'armada', origin: 'original', title: 'Zabrat statkářům půdu pro cvičiště',
    effects: { pop: { armada: 3, statkari: -3 }, str: { armada: 1, statkari: -1 } } },
  { id: 'p03', from: 'armada', origin: 'original', title: 'Zaútočit na všechny tábory povstalců v horách',
    effects: { cost: -100, pop: { armada: 3, rolnici: -1, statkari: 1, jugoslavie: -1, italie: -1 }, str: { armada: 1, statkari: 1, povstalci: -4 } } },
  { id: 'p04', from: 'armada', origin: 'original', title: 'Zaútočit na tábory povstalců za jugoslávskou hranicí',
    effects: { cost: -80, pop: { armada: 3, rolnici: -1, jugoslavie: -4, italie: -1 }, str: { armada: 1, statkari: 1, povstalci: -2 } } },
  { id: 'p05', from: 'armada', origin: 'original', title: 'Odvolat velitele tajné policie',
    effects: { pop: { armada: 4, rolnici: 2, statkari: 1, policie: -4 }, str: { armada: 1, statkari: 1, policie: -3 } } },
  { id: 'p06', from: 'armada', origin: 'original', title: 'Vyhostit italské vojenské poradce',
    effects: { pop: { armada: 3, jugoslavie: -1, italie: -4, britanie: 2 } } },
  { id: 'p07', from: 'armada', origin: 'original', title: 'Zvýšit vojákům žold',
    effects: { monthly: 9, pop: { armada: 4, statkari: -1 }, str: { armada: 2, rolnici: -1, statkari: -1, povstalci: -1 } } },
  { id: 'p08', from: 'armada', origin: 'original', title: 'Nakoupit více pušek a střeliva',
    effects: { cost: -120, pop: { armada: 4, rolnici: -1, statkari: -1, jugoslavie: -1, policie: -1 }, str: { armada: 3, rolnici: -1, statkari: -1, povstalci: -2, jugoslavie: -1 } } },
  // Rolníci (9–16)
  { id: 'p09', from: 'rolnici', origin: 'original', title: 'Zastavit násilné odvody mladých mužů do armády',
    effects: { pop: { armada: -1, rolnici: 2, statkari: 1 }, str: { armada: -1, povstalci: -1 } } },
  { id: 'p10', from: 'rolnici', origin: 'original', title: 'Zvýšit nejnižší mzdu',
    effects: { pop: { rolnici: 4, statkari: -4, jugoslavie: 1 }, str: { rolnici: 2, statkari: -1 } } },
  { id: 'p11', from: 'rolnici', origin: 'original', title: 'Omezit pravomoci tajné policie',
    effects: { monthly: -3, pop: { armada: 1, rolnici: 4, statkari: 2, policie: -4 }, str: { armada: 1, rolnici: 1, statkari: 1, povstalci: 1, policie: -3 } } },
  { id: 'p12', from: 'rolnici', origin: 'original', title: 'Nepouštět k nám dělníky z Jugoslávie',
    effects: { pop: { rolnici: 3, statkari: -2, jugoslavie: -2 }, str: { rolnici: 2, statkari: -2 } } },
  { id: 'p13', from: 'rolnici', origin: 'original', title: 'Zavést bezplatné školy pro všechny děti',
    effects: { cost: -100, monthly: 8, pop: { armada: -1, rolnici: 4, statkari: -2, jugoslavie: 2, policie: -1, italie: 1 }, str: { rolnici: 1, statkari: -1, povstalci: -1 } } },
  { id: 'p14', from: 'rolnici', origin: 'original', title: 'Povolit rolnické spolky a odbory',
    effects: { pop: { rolnici: 4, statkari: -3, jugoslavie: 1, policie: -1, italie: 1 }, str: { rolnici: 3, statkari: -3, policie: -1 } } },
  { id: 'p15', from: 'rolnici', origin: 'original', title: 'Propustit jejich uvězněného vůdce',
    effects: { pop: { armada: -1, rolnici: 4, statkari: -2, jugoslavie: 1, policie: -1 }, str: { rolnici: 2, statkari: -1, povstalci: -1 } } },
  { id: 'p16', from: 'rolnici', origin: 'original', title: 'Založit státní loterii',
    effects: { income: 6, pop: { rolnici: 3, statkari: -1 }, str: { povstalci: -1 } } },
  // Statkáři (17–24)
  { id: 'p17', from: 'statkari', origin: 'original', title: 'Zakázat armádě cvičit na jejich pozemcích',
    effects: { pop: { armada: -2, statkari: 3 }, str: { armada: -1 } } },
  { id: 'p18', from: 'statkari', origin: 'original', title: 'Snížit nejnižší mzdu',
    effects: { pop: { rolnici: -4, statkari: 4, jugoslavie: -1, italie: -1 }, str: { rolnici: -2, statkari: 2, povstalci: 1 } } },
  { id: 'p19', from: 'statkari', origin: 'original', title: 'Znárodnit britské podniky',
    effects: { cost: 100, monthly: 5, pop: { statkari: 3, jugoslavie: 1, italie: 2, britanie: -4 }, str: { statkari: 1 } } },
  { id: 'p20', from: 'statkari', origin: 'original', title: 'Uvalit clo na všechno zboží z Jugoslávie',
    effects: { income: 5, pop: { statkari: 3, jugoslavie: -3, italie: -1 }, str: { rolnici: 1, statkari: 2, jugoslavie: -1 } },
    // Capped at 3 accepted, and feeds the yearly tariff penalty (our addition, play-test change; tariffs plan).
    maxAccepted: 3, tariff: true },
  { id: 'p21', from: 'statkari', origin: 'original', title: 'Snížit výdaje na tajnou policii',
    effects: { monthly: -4, pop: { armada: 1, rolnici: 1, statkari: 3, policie: -4 }, str: { armada: 1, statkari: 1, povstalci: 1, policie: -2 } } },
  { id: 'p22', from: 'statkari', origin: 'original', title: 'Snížit vysoké pozemkové daně',
    effects: { income: -5, pop: { statkari: 4 }, str: { statkari: 2 } } },
  { id: 'p23', from: 'statkari', origin: 'original', title: 'Poslat vojáky pracovat na pole',
    effects: { pop: { armada: -2, rolnici: -1, statkari: 3 }, str: { armada: -1, rolnici: -1, statkari: 1, povstalci: 1 } } },
  { id: 'p24', from: 'statkari', origin: 'original', title: 'Postavit velké zavlažovací kanály',
    effects: { cost: -120, monthly: 10, pop: { armada: 1, rolnici: 1, statkari: 3, jugoslavie: -3, italie: 2, britanie: 1 }, str: { statkari: 3, jugoslavie: -2 } } },
  // Remake (pelikalkkuna/dictator), re-themed for Albania
  { id: 'r01', from: 'armada', origin: 'remake', title: 'Vyhodit statkáře z krajských úřadů',
    effects: { pop: { armada: 3, statkari: -3, rolnici: 1 } } },
  { id: 'r02', from: 'armada', origin: 'remake', title: 'Koupit armádě britské vysílačky',
    effects: { cost: -40, pop: { armada: 3, britanie: 2, italie: -3 }, str: { armada: 1 } } },
  { id: 'r03', from: 'armada', origin: 'remake', title: 'Dát vysloužilým vojákům půdu',
    effects: { pop: { armada: 3, statkari: -3, rolnici: 1 }, str: { armada: 1, statkari: -1 } } },
  { id: 'r04', from: 'armada', origin: 'remake', title: 'Uspořádat velkou vojenskou přehlídku v Tiraně',
    effects: { cost: -30, pop: { armada: 2, rolnici: 1, jugoslavie: -1 } } },
  { id: 'r05', from: 'armada', origin: 'remake', title: 'Vyhodit z důstojnického sboru přátele Itálie',
    effects: { pop: { armada: 3, jugoslavie: -2, italie: -2 }, str: { armada: -1, povstalci: 1 } } },
  { id: 'r06', from: 'armada', origin: 'remake', title: 'Uspořádat společné manévry s britskou armádou',
    effects: { cost: -15, pop: { armada: 2, rolnici: -1, britanie: 3, italie: -3 }, str: { armada: 1 } } },
  { id: 'r07', from: 'armada', origin: 'remake', title: 'Rozehnat studentské protesty v Tiraně',
    effects: { cost: -5, pop: { armada: 3, rolnici: -4, statkari: 1 }, str: { armada: 1, rolnici: -1 } } },
  { id: 'r08', from: 'rolnici', origin: 'remake', title: 'Zřídit venkovské nemocnice',
    effects: { cost: -80, monthly: 5, pop: { rolnici: 4, statkari: -2, italie: 1 }, str: { povstalci: -1 } } },
  { id: 'r09', from: 'rolnici', origin: 'remake', title: 'Rozdělit ladem ležící půdu rolnickým družstvům',
    effects: { pop: { rolnici: 4, statkari: -4, britanie: -1 }, str: { rolnici: 1, statkari: -1 } } },
  { id: 'r10', from: 'rolnici', origin: 'remake', title: 'Stanovit nejvyšší ceny chleba a soli',
    effects: { monthly: 5, pop: { rolnici: 3, statkari: -2 } } },
  { id: 'r11', from: 'rolnici', origin: 'remake', title: 'Zahájit kampaň proti negramotnosti',
    effects: { cost: -40, pop: { rolnici: 3, statkari: -1 }, str: { povstalci: -1 } } },
  { id: 'r12', from: 'rolnici', origin: 'remake', title: 'Podpořit drobné rolníky osivem a hnojivem',
    effects: { cost: -25, pop: { rolnici: 3, statkari: -1 }, str: { rolnici: 1 } } },
  { id: 'r13', from: 'rolnici', origin: 'remake', title: 'Usadit jugoslávské přistěhovalce v pohraničních vesnicích',
    effects: { pop: { rolnici: 2, armada: -2, statkari: -2, jugoslavie: 3 }, str: { rolnici: 1, jugoslavie: -1 } } },
  { id: 'r14', from: 'rolnici', origin: 'remake', title: 'Znárodnit britskou vodárenskou společnost',
    effects: { cost: 15, pop: { rolnici: 4, statkari: -1, britanie: -3 }, str: { rolnici: 1 } } },
  { id: 'r15', from: 'statkari', origin: 'remake', title: 'Vysušit bažiny pro nové olivové háje',
    effects: { income: 4, pop: { statkari: 3, rolnici: -2, jugoslavie: -1 }, str: { statkari: 1 } } },
  { id: 'r16', from: 'statkari', origin: 'remake', title: 'Prodat Britům monopol na tabák',
    effects: { cost: 80, pop: { statkari: 2, rolnici: -2, britanie: 3, italie: -3 } } },
  { id: 'r17', from: 'statkari', origin: 'remake', title: 'Rozehnat stávku na naftových polích v Kuçově',
    effects: { pop: { statkari: 3, rolnici: -3, policie: 1 }, str: { statkari: 1, rolnici: -1 } } },
  { id: 'r18', from: 'statkari', origin: 'remake', title: 'Zničit pašerácké stezky povstalců na jejich pozemcích',
    effects: { cost: -20, pop: { statkari: 3, armada: -1 }, str: { statkari: 1, povstalci: -2 } } },
  { id: 'r19', from: 'statkari', origin: 'remake', title: 'Dát daňové úlevy cizím investorům',
    effects: { income: -3, pop: { statkari: 3, rolnici: -2, britanie: 2 }, str: { statkari: 1 } } },
  { id: 'r20', from: 'statkari', origin: 'remake', title: 'Vyhostit vůdce rolnických spolků',
    effects: { pop: { statkari: 3, rolnici: -3, jugoslavie: -2 }, str: { statkari: 1, rolnici: -1 } } },
  // New, from Albanian history (our design)
  { id: 'a01', from: 'armada', origin: 'new', title: 'Postavit vojenskou silnici do hor Mirdity',
    effects: { cost: -60, pop: { armada: 3, rolnici: 1, statkari: -1 }, str: { armada: 1, povstalci: -2 } } },
  { id: 'a02', from: 'armada', origin: 'new', title: 'Odzbrojit horské klany',
    effects: { pop: { armada: 3, rolnici: -2, statkari: -2 }, str: { armada: 1, rolnici: -1, povstalci: -3 } } },
  { id: 'a03', from: 'armada', origin: 'new', title: 'Poslat mladé důstojníky na studia do Itálie',
    effects: { cost: -20, pop: { armada: 3, italie: 2, britanie: -1 }, str: { armada: 1 } } },
  { id: 'a04', from: 'armada', origin: 'new', title: 'Najmout české instruktory ze Zbrojovky Brno',
    effects: { cost: -30, pop: { armada: 3, italie: -1 }, str: { armada: 2 } } },
  { id: 'a05', from: 'armada', origin: 'new', title: 'Zesílit hlídky na jugoslávské hranici',
    effects: { monthly: 4, pop: { armada: 2, jugoslavie: -2 }, str: { armada: 1, jugoslavie: -1 } } },
  { id: 'a06', from: 'rolnici', origin: 'new', title: 'Postavit v každém kraji albánskou školu',
    effects: { cost: -60, pop: { rolnici: 4, statkari: -1, italie: -2 }, str: { povstalci: -1 } } },
  { id: 'a07', from: 'rolnici', origin: 'new', title: 'Snížit desátek z úrody',
    effects: { income: -4, pop: { rolnici: 4, statkari: -1 }, str: { rolnici: 1 } } },
  { id: 'a08', from: 'rolnici', origin: 'new', title: 'Vysušit malarické bažiny u Durrësu',
    effects: { cost: -50, pop: { rolnici: 3, statkari: 1 }, str: { rolnici: 1 } } },
  { id: 'a09', from: 'rolnici', origin: 'new', title: 'Zakázat krevní mstu',
    effects: { pop: { rolnici: 3, armada: -1, statkari: -2, policie: 1 }, str: { povstalci: -1 } } },
  { id: 'a10', from: 'rolnici', origin: 'new', title: 'Otevřít trh s tabákem drobným pěstitelům',
    effects: { income: 2, pop: { rolnici: 3, statkari: -3 }, str: { rolnici: 1, statkari: -1 } } },
  { id: 'a11', from: 'rolnici', origin: 'new', title: 'Pustit rolníky do lesů bejů',
    effects: { pop: { rolnici: 4, statkari: -4 }, str: { rolnici: 1, statkari: -1 } } },
  { id: 'a12', from: 'statkari', origin: 'new', title: 'Vrátit bejům půdu z pozemkové reformy',
    effects: { pop: { statkari: 4, rolnici: -4 }, str: { statkari: 2, rolnici: -1 } } },
  { id: 'a13', from: 'statkari', origin: 'new', title: 'Dovolit bejům vybírat mýto na cestách',
    effects: { income: -2, pop: { statkari: 3, rolnici: -2 }, str: { statkari: 1 } } },
  { id: 'a14', from: 'statkari', origin: 'new', title: 'Postavit ve Vloře přístav pro vývoz oleje',
    effects: { cost: -100, income: 4, pop: { statkari: 3, italie: 1 }, str: { statkari: 1 } } },
  { id: 'a15', from: 'statkari', origin: 'new', title: 'Jmenovat bejy prefekty krajů',
    effects: { pop: { statkari: 4, armada: -2, policie: -1 }, str: { statkari: 1, policie: -1 } } },
  { id: 'a16', from: 'statkari', origin: 'new', title: 'Uvalit clo na italské zboží', maxAccepted: 3, tariff: true,
    effects: { income: 5, pop: { statkari: 3, italie: -3 }, str: { statkari: 1 } } },
];

export const DECISIONS: readonly Decision[] = [
  // 1 Please a group
  { id: 'd25', section: 1, origin: 'original', title: 'Jmenovat velitele armády svým zástupcem',
    effects: { pop: { armada: 4, rolnici: -1, statkari: -1, policie: -1 }, str: { armada: 1, povstalci: -1, policie: -1 } } },
  { id: 'd26', section: 1, origin: 'original', title: 'Zřídit bezplatné ošetřovny pro dělníky',
    effects: { cost: -10, monthly: 4, pop: { armada: -1, rolnici: 4, statkari: 1, jugoslavie: 2, italie: 1 }, str: { povstalci: -1 } } },
  { id: 'd27', section: 1, origin: 'original', title: 'Dát statkářům moc v krajích',
    effects: { pop: { armada: -1, rolnici: -2, statkari: 4, policie: -1, italie: -1 }, str: { armada: -1, rolnici: -1, statkari: 2, policie: -1 } } },
  { id: 'd28', section: 1, origin: 'original', title: 'Prodat britské zbraně Jugoslávii',
    effects: { cost: 50, pop: { armada: -2, jugoslavie: 4, italie: -2, britanie: 1 }, str: { armada: -1, povstalci: -1, jugoslavie: 3 } } },
  { id: 'd29', section: 1, origin: 'original', title: 'Prodat Britům právo těžit naftu',
    effects: { cost: 120, pop: { statkari: -1, jugoslavie: -1, italie: -2, britanie: 3 } } },
  { id: 'd30', section: 1, origin: 'original', title: 'Pronajmout Italům ostrov Sazan pro námořnictvo',
    effects: { income: 10, pop: { armada: -2, italie: 3, britanie: -3 }, str: { jugoslavie: 1 } } },
  // 2 Please all groups
  { id: 'd31', section: 2, origin: 'original', title: 'Snížit daně všem',
    effects: { income: -8, pop: { armada: 1, rolnici: 3, statkari: 3 }, str: { armada: -1, povstalci: -1 } } },
  { id: 'd32', section: 2, origin: 'original', title: 'Uspořádat velkou oslavnou kampaň',
    effects: { cost: -80, pop: { armada: 3, rolnici: 3, statkari: 3 }, str: { povstalci: -1 } } },
  { id: 'd33', section: 2, origin: 'original', title: 'Úplně zrušit pravomoci tajné policie',
    effects: { monthly: -8, pop: { armada: 3, rolnici: 3, statkari: 3, policie: -9 }, str: { armada: 2, rolnici: 1, statkari: 1, povstalci: 1, policie: -9 } } },
  // 3 Improve your chances
  { id: 'd34', section: 3, origin: 'original', title: 'Výrazně posílit tajnou policii',
    effects: { monthly: 6, pop: { armada: -3, rolnici: -3, statkari: -3, policie: 8 }, str: { armada: -1, rolnici: -1, statkari: -1, povstalci: -1, policie: 8 } } },
  { id: 'd35', section: 3, origin: 'original', title: 'Posílit osobní stráž', special: { kind: 'bodyguard' }, reusable: true,
    effects: { cost: -40, pop: { armada: -2, rolnici: -1, statkari: -1, policie: -1 }, str: { armada: -2, policie: -1 } } },
  { id: 'd36', section: 3, origin: 'original', title: 'Koupit letadlo pro útěk', special: { kind: 'plane' },
    effects: { cost: -120, pop: { armada: -4, rolnici: -4, statkari: -3, policie: -2 } } },
  { id: 'd37', section: 3, origin: 'original', title: 'Poslat peníze na švýcarský účet', special: { kind: 'swiss' }, reusable: true,
    effects: {} },
  // 4 Raise some cash
  { id: 'd38', section: 4, origin: 'original', title: 'Požádat Itálii o půjčku', special: { kind: 'aid', lender: 'italie' },
    effects: {} },
  { id: 'd39', section: 4, origin: 'original', title: 'Požádat Británii o pomoc', special: { kind: 'aid', lender: 'britanie' },
    effects: {} },
  { id: 'd40', section: 4, origin: 'original', title: 'Znárodnit jugoslávské podniky',
    effects: { cost: 130, pop: { armada: 1, rolnici: 1, statkari: 3, jugoslavie: -6, italie: -2 } } },
  // 5 Strengthen a group
  { id: 'd41', section: 5, origin: 'original', title: 'Koupit armádě těžká děla',
    effects: { cost: -50, pop: { armada: 3, jugoslavie: -3, italie: -1 }, str: { armada: 5, povstalci: -2, jugoslavie: -2, policie: -1 } } },
  { id: 'd42', section: 5, origin: 'original', title: 'Dovolit rolníkům volně se stěhovat',
    effects: { pop: { rolnici: 3, statkari: -1, policie: -1 }, str: { rolnici: 5, statkari: -1, povstalci: 3, policie: -1 } } },
  { id: 'd43', section: 5, origin: 'original', title: 'Dovolit statkářům soukromé ozbrojené družiny',
    effects: { pop: { armada: -1, rolnici: -1, statkari: 3, policie: -1 }, str: { armada: -1, rolnici: -1, statkari: 5, povstalci: -1, policie: -1 } } },
];

export const NEWS: readonly NewsItem[] = [
  { id: 'n44', origin: 'original', title: 'Král ztratil tajné spisy četnictva',
    effects: { pop: { policie: -4 }, str: { povstalci: 4, policie: -4 } } },
  { id: 'n45', origin: 'original', title: 'Exulanti v Bari vyzbrojili a vycvičili povstalce',
    effects: { str: { armada: -1, povstalci: 9 } } },
  { id: 'n46', origin: 'original', title: 'Neštěstí: vybuchla kasárna',
    effects: { str: { armada: -4, povstalci: 2, policie: 1 } } },
  { id: 'n47', origin: 'original', title: 'Ceny tabáku klesly o 98 %',
    effects: { str: { statkari: -3, jugoslavie: -2 } } },
  { id: 'n48', origin: 'original', title: 'Velké zemětřesení v Jugoslávii',
    effects: { str: { statkari: 2, jugoslavie: -4 } } },
  { id: 'n49', origin: 'original', title: 'Vesnice zasáhla epidemie',
    effects: { str: { rolnici: -4, statkari: -1, povstalci: -2 } } },
];
